### ISSUE TITLE
UX Planning checklist

### ISSUE THREAD

**Issue by Nimisoere** [college-portal/ux-prototype#3]
### UX Checklist

- [x] **UX Research**
  - [x] Review similar projects - :white_check_mark:
  - [x] Brainstorm and get users' opinions :white_check_mark:
  - [x] Define KPI [Link](https://docs.google.com/spreadsheets/d/1AsIvtKR0DqSt99AZdJJka42mOacUAkw3j4fxU7hwhMA/edit#gid=1699983326) :white_check_mark:
- [x] **Plan**
  - [x] Define user stories [Link](https://docs.google.com/spreadsheets/d/1AsIvtKR0DqSt99AZdJJka42mOacUAkw3j4fxU7hwhMA/edit?usp=sharing) :white_check_mark:
  - [ ] Define red routes  [Link](https://docs.google.com/spreadsheets/d/1AsIvtKR0DqSt99AZdJJka42mOacUAkw3j4fxU7hwhMA/edit#gid=1894864492) 
- [ ] **Prototype** (Done along side Con/Comm - UX)
  - [ ] Rough brainstorm sketch (Screen Planning)
  - [ ] Wireframe
  - [ ] Prototype
- [ ] **Content/Communication** (Done along side prototype - UI)
  - [ ] Define App language/persona - Youthful Persona (Pop culture/Generation Z) ✅ 
  - [ ] Define content strategy
  - [ ] Define Brand (colors, logos...) - Colors:Blue/Orange Font: Poppings :white_check_mark:
  - [ ] Get prototype approved (pre-development)
- [ ] **Create**
  - [ ] Define and Create reuseable components
  - [ ] Create static screens
  - [ ] Connect to APIs **
- [ ] **Refine**
  - [ ] Measure and Optimize performance
  - [ ] Get User feedback and refine
  - [ ] Measure against KPI
- [ ] **Razzmattaz**
  - [ ] Add transitions
  - [ ] Add micro interactions
  - [ ] Add micro copies
- [ ] **Analyse**
  - [ ] Define post launch KPIs
  - [ ] Define test plans
  - [ ] Include analytics

**Comment by Nimisoere** [comment]
Feedback and Testing happens at every phase
